using Xunit;

namespace Cloudless.Tests;

public sealed class CommandSyntaxValidatorTests
{
    [Theory]
    [InlineData("close")]
    [InlineData("close all")]
    [InlineData("goto start")]
    [InlineData("sort name asc")]
    [InlineData("sort date desc")]
    [InlineData("nudge left")]
    [InlineData("nudge down -12")]
    [InlineData("n 3 -2")]
    [InlineData("filmstrip recent")]
    [InlineData("ws load sample")]
    [InlineData("ws origin")]
    [InlineData("m origin")]
    [InlineData("set e")]
    [InlineData("goto f")]
    [InlineData("t l")]
    [InlineData("tag list")]
    [InlineData("hk ctrl left")]
    [InlineData("hotkey shift f1")]
    [InlineData("HOTKEY CTRL RIGHT")]
    [InlineData("filmstrip bookmarks")]
    [InlineData("fs p sample-workspace")]
    [InlineData("seek 1:30")]
    [InlineData("slideshow 5 shuffle")]
    [InlineData("slideshow next")]
    [InlineData("slideshow n")]
    [InlineData("ss n")]
    [InlineData("slideshow t")]
    [InlineData("ss s t")]
    [InlineData("slideshow triggers shuffle")]
    [InlineData("ss 5 t s")]
    [InlineData("slideshow 5 shuffle triggers")]
    [InlineData("p 2")]
    [InlineData("p 2 send")]
    [InlineData("p 2 bring")]
    [InlineData("p 2 swap 3")]
    [InlineData("tag add vacation")]
    [InlineData("all close")]
    [InlineData("others goto end")]
    [InlineData("close; goto start")]
    [InlineData("c2 set close all")]
    [InlineData("macro record demo close all")]
    public void RecognizesSyntacticallyCompleteCommands(string command)
    {
        Assert.True(CommandSyntaxValidator.IsValidCommand(command));
    }

    [Theory]
    [InlineData("")]
    [InlineData("asdf")]
    [InlineData("goto")]
    [InlineData("set")]
    [InlineData("tag")]
    [InlineData("t")]
    [InlineData("fs p")]
    [InlineData("filmstrip preview")]
    [InlineData("ws p")]
    [InlineData("hk ctrl")]
    [InlineData("hotkey ctrl definitely-not-a-key")]
    [InlineData("t add")]
    [InlineData("fs tag")]
    [InlineData("o tag")]
    [InlineData("close origin")]
    [InlineData("m empty")]
    [InlineData("um others")]
    [InlineData("seek")]
    [InlineData("sort")]
    [InlineData("sort name")]
    [InlineData("sort random asc")]
    [InlineData("nudge")]
    [InlineData("nudge sideways")]
    [InlineData("dm")]
    [InlineData("dm invalid")]
    [InlineData("ws")]
    [InlineData("ws load")]
    [InlineData("slideshow")]
    [InlineData("slideshow 0")]
    [InlineData("slideshow s")]
    [InlineData("ss shuffle")]
    [InlineData("slideshow 5 invalid")]
    [InlineData("close; asdf")]
    [InlineData("all")]
    [InlineData("c25 run")]
    public void RejectsUnknownOrIncompleteCommandSyntax(string command)
    {
        Assert.False(CommandSyntaxValidator.IsValidCommand(command));
    }
}
